### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by spirrello** [thepacketgeek/cloud-pcap#2]
Hi,

I've followed the steps provided however I still can't get past the login page.  Can you explain why this error message would appear?  I get this after I enter the default admin/cloudpcap login credentials.

sqlalchemy.exc.OperationalError
OperationalError: (OperationalError) fe_sendauth: no password supplied
 None None

![image](https://cloud.githubusercontent.com/assets/7174260/16961329/ff4e89f6-4dba-11e6-85e2-93bd0cb14c57.png)

**Comment by thepacketgeek** [comment]
Hmm, this is a PostgreSQL issue with auth. Check out these links for adding the correct auth for PostgreSQL on Centos:
http://stackoverflow.com/questions/23839656/sqlalchemy-no-password-supplied-error
http://stackoverflow.com/questions/33928585/python-and-postgresql-operationalerror-fe-sendauth-no-password-supplied

**Comment by thepacketgeek** [comment]
@spirrello Updating took me a while, but hopefully this issue is fixed with the new Docker deployment and PostgreSQL init steps
