### ISSUE TITLE
Put psql path in config.py DevelopmentConfig() class

### ISSUE THREAD

**Issue by louistone** [thepacketgeek/cloud-pcap#4]
Hi Mat,

I am using Mac and the path is  "/usr/local/var/postgres".
I tried below:

class DevelopmentConfig(Config):
	PATH =  '/usr/local/var/postgres'
	SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/cloud-pcap'

What's the right way to do it? Can you help?

Thanks,
Tong

**Comment by thepacketgeek** [comment]
HI @louistone, the path you're mentioning there is the path to the postgres executable which cloud-pcap does not need. That process should be running and cloud-pcap communicates over the SQLALCHEMY_DATABASE_URI path. You might need to update that path given the IP and port your postgresql process is listening on.

**Comment by louistone** [comment]
Thanks for your timely reply!
