### ISSUE TITLE
问题：没有找到pcap模块

### ISSUE THREAD

**Issue by AnZhanLiangJian** [thepacketgeek/cloud-pcap#6]
![123](https://user-images.githubusercontent.com/48705743/58896231-26265a00-8728-11e9-9926-81b9a7d21501.PNG)
搞不懂

**Comment by thepacketgeek** [comment]
https://pypi.org/project/pypcapfile/

`pip install pcapfile`

**Comment by AnZhanLiangJian** [comment]
问题已解决，谢谢



------------------ 原始邮件 ------------------
发件人: "Mat Wood"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 凌晨1:24
收件人: "thepacketgeek/cloud-pcap"<cloud-pcap@noreply.github.com>;
抄送: "李世浩"<760650615@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [thepacketgeek/cloud-pcap] 问题：没有找到pcap模块 (#6)




https://pypi.org/project/pypcapfile/
 
pip install pcapfile
