### ISSUE TITLE
what？

### ISSUE THREAD

**Issue by AnZhanLiangJian** [thepacketgeek/cloud-pcap#7]
![123](https://user-images.githubusercontent.com/48705743/58896465-9f25b180-8728-11e9-8925-8af36f4903c9.PNG)
请问？这是什么原因

**Comment by thepacketgeek** [comment]
@AnZhanLiangJian, check out the installation instructions in the README, you need to export `APP_SETTINGS`:

E.g.
`$ export APP_SETTINGS="config.DevelopmentConfig"`
