### ISSUE TITLE
ProgrammingError:

### ISSUE THREAD

**Issue by nightRainy** [thepacketgeek/cloud-pcap#8]
Hi,
    I've followed the steps provided however I still can't get past the login page either.
    I think may be i can't write datas into my database,Can u help me?

![image](https://user-images.githubusercontent.com/44838179/62955803-452a2200-be24-11e9-9d96-0b678904f710.png)

**Comment by thepacketgeek** [comment]
Have you run the `init_db` and `db.session.commit()` commands from the Installation section? The dependencies are 5+ years old though, it might just be something broken between the app and PostgreSQL

**Comment by nightRainy** [comment]
> Have you run the `init_db` and `db.session.commit()` commands from the Installation section? The dependencies are 5+ years old though, it might just be something broken between the app and PostgreSQL

Thanks for u reply . I did it, but it didn't seem to work, it might be a matter of time.
